django_level_three/DB_Connected_Form/DB_Connected_Form/urls.py
from django.contrib import admin
from django.urls import path,include
from db_forms import views

urlpatterns = [
    path('',include('db_forms.urls')),
    path('admin/', admin.site.urls),
]

django_level_three/DB_Connected_Form/db_forms/urls.py
from django.urls import path
from db_forms import views
app_name = 'db_forms'
urlpatterns=[
    path('',views.index,name = "index"),
    path('/formpage',views.formpage,name = "formpage"),
    path('/other',views.other,name='other'),
]

django_level_three/DB_Connected_Form/db_forms/models.py
from django.db import models

# Create your models here.
class users(models.Model):
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length =20)
    email = models.CharField(max_length = 40,unique =True)

    def __str__(self):
        return str(self.email)

django_level_three/DB_Connected_Form/db_forms/views.py
from django.shortcuts import render
from .models import users
# Create your views here.
def index(request):
    return render (request,'db_forms/index.html')

def formpage(request):
    error = {"email_error": ""}
    if request.method == 'POST':
        if not users.objects.get_or_create(firstname = request.POST['fname'],lastname=request.POST['lname'],email = request.POST['email'])[1] :
            error['email_error']="Email already exists"
            return render(request,'db_forms/formpage.html',error)
        else:
            error['email_error']=""
            return login(request)
    return render(request,'db_forms/formpage.html',error)

def login(request):
    return render(request,'db_forms/login.html')

def other(request):
    return render(request,'db_forms/other.html')

django_level_three/DB_Connected_Form/db_forms/templates/db_forms/formpage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>User Registration</title>
  </head>
  <body>
    <form action="" method="post">
      {%csrf_token%}
      <label>First Name:</label>
      <input type="text" name="fname" value="" placeholder="First Name" required>
      <p></p>
      <label>Last Name:</label>
      <input type="text" name="lname" value="" placeholder="Last Name">
      <p></p>
      <label>Email:</label>
      <input type="email" name="email" value="" placeholder="Email" required>
      {{email_error}}
      <p></p>
      <input type="submit" name="" value="Register">
    </form>
  </body>
</html>

django_level_three/DB_Connected_Form/db_forms/templates/db_forms/index.html
  {%extends 'db_forms/login.html' %}
  {% block content %}

      <h1>Please go to /formpage to enter the details</h1>
    {% endblock %}

django_level_three/DB_Connected_Form/db_forms/templates/db_forms/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'db_forms:index' %}">Django</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'db_forms:formpage' %}">Register</a>
      </li>
    </ul>
  </div>
</nav>
    <div class="container">
      {% block content%}
      <h1>Logged in </h1>
      <a href="{% url 'db_forms:other' %}">Formpage</a>
      {% endblock %}
    </div>

  </body>
</html>

django_level_three/DB_Connected_Form/db_forms/templates/db_forms/other.html
<!DOCTYPE html>
{% extends 'db_forms/login.html' %}
{% block content %}
    <h1>welcome to other page </h1>
{% endblock %}