django_level_five/register_and_login/register_and_login/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('',include('webapp.urls')),
    path('admin/', admin.site.urls),
]

django_level_five/register_and_login/webapp/urls.py
from django.urls import path
from webapp import views
app_name = 'webapp'

urlpatterns=[
    path ('',views.index,name="index"),
    path('register/',views.register,name ="register"),
    path('login/',views.login,name = "login"),
    path('other/',views.other,name = "other"),
]

django_level_five/register_and_login/webapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfoForm(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(blank=True)
    def __str__(self):
        return self.user.username

django_level_five/register_and_login/webapp/forms.py
from django import forms
from django.contrib.auth.models import User
from webapp.models import UserProfileInfoForm

class UserForm(forms.ModelForm):
    password = forms.CharField(widget  = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','first_name','last_name','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfoForm
        fields = ('portfolio_site','profile_pic')

django_level_five/register_and_login/webapp/views.py
from django.shortcuts import render
from webapp.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request, 'webapp/index.html')

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid() :
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form= UserProfileInfoForm()
    return render(request,'webapp/register.html',{'user':user_form,'profile':profile_form,'registered':registered})

def login(request):
    active = False
    if request.method == "POST":
        user_status = authenticate(username = request.POST['username'], password= request.POST['password'])
        if user_status:
            login(request,user)
            return HttpResponseRedirect(reverse('index',{'active':active}))
    return render(request,'webapp/login.html',{'active':active})

def other(request):
    return render(request,'webapp/other.html')

django_level_five/register_and_login/webapp/templates/webapp/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{%  url 'webapp:index' %}">Django</a>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'webapp:register' %}">Register</a>
      <a class="nav-item nav-link" href="{% url 'webapp:login' %}">Login</a>
      {% if active %}
      <a class="nav-item nav-link" href="{% url 'webapp:login' %}">Other</a>
      {%endif%}
    </div>
  </div>
</nav>
  {% block content %}
  <h1>This is Index.html</h1>
  {% endblock %}
  </body>
</html>

django_level_five/register_and_login/webapp/templates/webapp/login.html
<!DOCTYPE html>
{% extends 'webapp/index.html' %}
{% block content %}
{% if not active %}
<div class="jumbotron">
  <form  method="post">
    {%csrf_token%}
    <label for="username">User Name : </label>
    <input type="text" name="username" value="">
    <br>
    <label for="password">Password : </label>
    <input type="password" name="password" value="">
    <br>
    <input type="submit" name="" value="Login">
  </form>
</div>
{% else %}
<h1>User logged in </h1>
{% endif %}
{% endblock %}

django_level_five/register_and_login/webapp/templates/webapp/register.html
<!DOCTYPE html>
{% extends 'webapp/index.html' %}
{% block content %}

<div class="jumbotron">
  {% if registered %}
  <h1>Thank You for Registering</h1>
  {% else %}
  <h1>Register Here</h1>
  <h3>Fill out the Form!!</h3>
  <form enctype="multipart/form-data" method="post">
    {%csrf_token%}
    {{user.as_p}}
    {{profile.as_p}}
    <input type="submit" name="" value="">
  </form>

  {% endif %}
</div>
{% endblock %}